#!/usr/bin/env bash
# KAMMAND model router.
# Fires on UserPromptSubmit. Emits a routing rubric as additionalContext so the
# session classifies each task and dispatches it to a model matched to its cost.
# Reads (and ignores) the hook payload on stdin; emits static JSON. No deps.
cat >/dev/null 2>&1 || true

cat <<'JSON'
{"suppressOutput":true,"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext":"<model-routing>\nBefore acting on this request, classify it into ONE tier and route it. State the tier and model in one short line (e.g. `Route: T2 -> sonnet`) before you start. Do not re-state the rubric.\n\nT0 TRIVIAL — answer or act inline on the current model. No subagent.\n  Questions about the repo, reading a file, a one-line edit, a git status, restating prior work.\n\nT1 ROUTINE — Agent(subagent_type: 'general-purpose', model: 'haiku').\n  Mechanical and fully specified, one or two files, no judgment: rename a symbol,\n  add a test case mirroring an existing one, fix a lint error, update copy in a\n  content file, bump a version, grep-and-report.\n\nT2 STANDARD — Agent(subagent_type: 'general-purpose', model: 'sonnet').\n  Multi-file but the pattern already exists in the repo: a new page from an\n  existing template (services/frameworks/industries all have one), a component\n  built to an approved SPEC, a failing test with a known cause, wiring an\n  existing lib helper into a route.\n\nT3 COMPLEX — stay on opus (this session), or Agent(model: 'opus') to parallelize.\n  Ambiguous scope, cross-cutting change, architecture or spec authoring,\n  debugging with unknown cause, accessibility or performance work, anything\n  where getting it wrong is expensive to unwind.\n\nESCALATE TO T3 REGARDLESS OF SIZE when the task touches:\n  kammand-security/app/globals.css or any design token; docs/specs/**;\n  kammand-security/lib/leads/**, lib/consent/**, lib/env.ts, lib/integrations/**;\n  kammand-security/app/api/**; next.config.ts; .github/workflows/**;\n  security headers, secrets, or input validation; git history, branches, or PRs.\n\nRULES\n  - Route once per task, not per tool call. A follow-up on the same task keeps its tier.\n  - When torn between two tiers, take the higher one.\n  - Delegating is optional at T0/T3; at T1/T2 prefer the subagent so this session\n    stays on the expensive model only for work that needs it.\n  - Every tier above T0 that changes code must pass the AGENTS.md gate before you\n    report done, run from kammand-security/:\n      npm run lint && npm run typecheck && npm run test && npm run build\n    Report real results. A skipped or failing gate must be stated, not glossed.\n  - AGENTS.md is binding on the subagent too — tell it so in the prompt you write.\n</model-routing>"}}
JSON
